# fly.toml app configuration file generated for planning-poker-rails-newbie on 2023-05-04T10:45:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "planning-poker-rails-newbie"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
